fail start if nopde already running

diff --git a/geth/template/start.template b/geth/template/start.template
--- a/geth/template/start.template
+++ b/geth/template/start.template
@@ -14,6 +14,9 @@ geth_port=:geth_port:
 
 [ "${geth_args}" == ":geth_args:" ]  && echo "[${_LOGPREFIX}] ERROR: Can not execute template script" && exit 2
 
+_PID=$(ps -ef | grep "[d]atadir ${geth_datadir}" | awk '{print $2}')
+[ "${_PID}" != "" ] && echo "[${_LOGPREFIX}] ERROR: This node appears to be running already as PID: [${_PID}]" && exit 3
+
 _CLUSTERSTATIC=${_CLUSTERDIR}/static-nodes.json
 _NODESTATIC=${_NODEDIR}/static-nodes.json
 
@@ -25,9 +28,11 @@ geth_log=${geth_datadir}/${_CLUSTERID}-${_NODEID}.log
 
 geth_cmdline="geth --datadir ${geth_datadir} ${geth_args} ${@}"
 
+
 echo "[${_LOGPREFIX}] Running GETH command ..." | tee -a ${geth_log}
 echo "${geth_cmdline}" | tee -a ${geth_log}
 
-eval "${geth_cmdline} &>> ${geth_log} &" 
+eval "${geth_cmdline} &>> ${geth_log} &"
 
-echo "[${_LOGPREFIX}] SUCCESS; Geth output available in [${geth_log}]" | tee -a ${geth_log}
+_PID=$(ps -ef | grep "[d]atadir ${geth_datadir}" | awk '{print $2}')
+echo "[${_LOGPREFIX}] SUCCESS; geth pid: [${_PID}], logfile: [${geth_log}]" | tee -a ${geth_log}
